app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, Length
from app import db
from app.models import User
import sqlalchemy as sa

from flask_babel import lazy_gettext as l_

class EditProfileForm(FlaskForm):
    username = StringField(l_('Username'), validators=[DataRequired()])
    bio = TextAreaField(l_('Bio'))
    submit = SubmitField(l_('Submit'))

    def __init__(self, original_username, *args, **kwargs):
        
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        
        if username.data != self.original_username:
            query = sa.select(User).where(User.username == username.data)
            user = db.session.scalars(query).one_or_none()

            if user:
                raise ValidationError(l_("Please use another username"))
            

class MessageForm(FlaskForm):
    body = TextAreaField(l_("Your message"), validators=[DataRequired()])
    submit = SubmitField()


class FollowForm(FlaskForm):
    submit = SubmitField()

app/user/__init__.py
from flask import Blueprint

user_bp = Blueprint('user_bp', __name__,
                    template_folder='templates',
                    static_folder='static')

from app.user import forms, routes

app/user/routes.py
from app.models import User, Goal, Message, Notification
from app import db
from flask_login import login_required, current_user
import sqlalchemy as sa
from flask import url_for, render_template, redirect, flash, request, current_app, jsonify

from app.user import user_bp
from app.user.forms import EditProfileForm, FollowForm, MessageForm

from datetime import datetime, timezone

from flask_babel import _


@user_bp.route('/user/<username>', methods=['GET'])
@login_required
def user(username):
    query = sa.select(User).where(User.username == username)
    user = db.one_or_404(query)

    goals_query = user.goals.select().order_by(sa.desc(Goal.timestamp))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['GOALS_PER_PAGE']
    goals = db.paginate(goals_query, 
                        page=page,
                        per_page=per_page,
                        error_out=False
    )

    form = FollowForm()

    prev_url = url_for('user_bp.user', page=goals.prev_num, username=username)\
                if goals.has_prev else None
    next_url = url_for('user_bp.user', page=goals.next_num, username=username)\
                if goals.has_next else None
    
    return render_template('user/user.html', user=user, goals=goals, form=form,
                           prev_url=prev_url, next_url=next_url)


@user_bp.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):

    form = FollowForm()

    if form.validate_on_submit():
        query = sa.select(User).where(User.username == username)
        user = db.session.scalar(query)
        if not user:
            # flash(f'{user.username} not found')
            flash(_('%(username)s not found',  username=user.username))
            return redirect(url_for('main_bp.index'))
        elif current_user.id == user.id:
            # flash(f'{user.username}, can not follow yourself')
            flash(_('%(username)s, can not follow yourself', username=user.username))
            return redirect(url_for('user_bp.user', username=username))
        else:
            current_user.follow(user)
            db.session.commit()
            # flash(f'{user.username} has been followed')
            flash(_('%(username)s has been followed', username=user.username))
            return redirect(url_for('user_bp.user', username=username))
            
    return redirect(url_for('main_bp.index'))
    
    

@user_bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):

    form = FollowForm()

    if form.validate_on_submit():
        query = sa.select(User).where(User.username == username)
        user = db.session.scalar(query)
        if not user:
            # flash(f'{user.username} not found')
            flash(_('%(username)s not found', username=user.username))
            return redirect(url_for('main_bp.index'))
        elif current_user.id == user.id:
            # flash(f'{user.username}, can not unfollow yourself')
            flash(_('%(username)s, can not follow yourself', username=user.username))
            return redirect(url_for('user_bp.user', username=username))
        else:
            current_user.unfollow(user)
            db.session.commit()
            # flash(f'{user.username} has been unfollowed')
            flash(_('%(username)s has been unfollowed', username=user.username))
            return redirect(url_for('user_bp.user', username=username))
            
    return redirect(url_for('main_bp.index'))
    

@user_bp.route('/send_message/<username>', methods=['GET', 'POST'])
@login_required
def send_message(username):
    form = MessageForm()

    recipient = db.session.scalar(
                sa.select(User).where(User.username == username))
    
    if form.validate_on_submit():
        message = Message()
        message.author = current_user
        message.recipient = recipient
        message.body = form.body.data

        db.session.add(message)
        db.session.commit()

        cnt = recipient.count_unread_messages()
        recipient.add_notification("unread_messages_count", cnt)

        flash(_("Message sent"))

        return redirect(url_for('user_bp.user', username=recipient.username))

    return render_template("user/send_message.html", form=form, recipient=recipient)    
    

@user_bp.route('/user/messages', methods=['GET'])
@login_required
def messages():
    messages_query = current_user.messages_received.select().order_by(sa.desc(Message.timestamp))
    # incoming_messages = db.session.scalars(messages_query)
    current_user.last_read_messages = datetime.now(timezone.utc)
    db.session.commit()

    current_user.add_notification("unread_messages_count", 0)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['GOALS_PER_PAGE']
    incoming_messages = db.paginate(messages_query, 
                        page=page,
                        per_page=per_page,
                        error_out=False
    )

    form = FollowForm()

    prev_url = url_for('user_bp.messages', page=incoming_messages.prev_num)\
                if incoming_messages.has_prev else None
    next_url = url_for('user_bp.messages', page=incoming_messages.next_num)\
                if incoming_messages.has_next else None

    return render_template("user/messages.html", messages=incoming_messages,
                           prev_url=prev_url, next_url=next_url)

@user_bp.route('/user/notifications', methods=['GET'])
@login_required
def notifications():

    time_since = request.args.get('since', 0, type=int)
    notifications_query = current_user.notifications.select().where(
        Notification.timestamp >= time_since
    ).order_by(Notification.timestamp)

    user_notifications = db.session.scalars(notifications_query).all()

    return [{
        'name': n.name,
        'payload': n.payload,
        'timestamp': n.timestamp
    } for n in user_notifications]


@user_bp.route('/user/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():

    form = EditProfileForm(original_username=current_user.username)
    if request.method == 'GET':
        # Prepopulate
        form.username.data = current_user.username
        form.bio.data = current_user.bio
        
    if form.validate_on_submit():

        current_user.username = form.username.data    
        current_user.bio = form.bio.data

        db.session.commit()

        flash(_('Changes saved!'), category='info')
        return redirect(url_for('user_bp.edit_profile'))

    return render_template('user/edit_profile.html', form=form)


@user_bp.route('/user/export_goals', methods=['GET'])
@login_required
def export_goals():
    if current_user.get_task_in_progress("app.tasks.export_goals"):
        flash(_("You have already exporting in progress"))
    else:
        print(current_app.config['SQLALCHEMY_DATABASE_URI'])
        current_user.start_task(task_name="app.tasks.export_goals", task_description=_("Exporting goals"))
        db.session.commit()
    return redirect(url_for("user_bp.user", username=current_user.username))


@user_bp.route('/user/<username>/mini_profile', methods=['GET'])
@login_required
def mini_profile(username):
    user = db.first_or_404(sa.select(User).where(User.username==username))
    form = FollowForm()
    return render_template('/user/user_mini_profile.html', user=user, form=form)


@user_bp.before_request
def update_last_seen():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now(timezone.utc)
        db.session.commit()

app/templates/_formhelpers.html
{% macro render_submit_field(field) %}
  {{ field(class_="btn btn-primary") }}
{% endmacro %}

{% macro render_generic_field(field) %}
    {{ field.label(class='form-label') }}
    {{ field(class_="form-control") }}
    {% for error in field.errors %}
      <span style="color: red">{{ error }}</span>
    {% endfor %}
{% endmacro %}

{% macro render_text_area_field(field) %}
  {{ field.label(class='form-label') }}
  {{ field(class_="form-control", cols=50, rows=5) }}
  {% for error in field.errors %}
    <span style="color: red">{{ error }}</span>
  {% endfor %}
{% endmacro %}

{% macro render_checkbox_field(field) %}
  <div class="form-check">
    {{ field(class_="form-check-input") }} 
    {{ field.label(class_="form-check-label") }}
  </div>
{% endmacro %}

{% macro render_field(field) %}
  {% if field.type == "SubmitField" %}
      {{ render_submit_field(field) }}
  {% elif field.type == "TextAreaField" %}
      {{ render_text_area_field(field) }}
  {% elif field.type == "BooleanField" %}
      {{ render_checkbox_field(field) }}
  {% else %}
      {{ render_generic_field(field) }}
  {% endif %}
  
{% endmacro %}

{% macro render_form(form) %}
  <form action="" method="post" novalidate>
    <div class="form-group">
      {{ form.hidden_tag() }}
      {% for field in form %}
        {% if field.widget.input_type != "hidden" %}
          <div class="mb-3">
            {{ render_field(field) }}
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </form>
{% endmacro %}

app/templates/_goal.html
<table>
  <tr>
  <td>
    <a href="{{ url_for('user', username=goal.author.username)}}">
      <img src="{{ goal.author.get_avatar(size=50) }}">
    </a>
  </td>
  <td>
    <p> 
    Author: <a href="{{ url_for('user', username=goal.author.username)}}">{{ goal.author.username }}</a> 
    </p>
    <p>text: {{ goal.body }} </p>
    <p>Created: {{ goal.timestamp }}</p>
  </td>
  </tr>
</table>

app/templates/_paginationhelpers.html
{% macro render_pagination(pagination, prev_url, next_url) %}
<nav aria-label="Goals pagination">
  <ul class="pagination">
    {% if pagination.has_prev %}
      <li class="page-item">
        <a class="page-link" href="{{ prev_url }}">Previous</a>
      </li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Previous</span></li>
    {% endif %}

    {% for page_num in pagination.iter_pages() %}
      {% if page_num %}
        {% if page_num != pagination.page %}
          <li class="page-item">
            <li class="page-item" aria-current="page">
              <span class="page-link">{{ page_num }}</span>
          </li>
            
          </li>
        {% else %}
          <li class="page-item active" aria-current="page">
              <span class="page-link">{{ page_num }}</span>
          </li>
        {% endif %}
      {% else %}
        <!-- For gaps in the pagination links, show ellipsis -->
        <li class="page-item disabled"><span class="page-link">...</span></li>
      {% endif %}
    {% endfor %}

    {% if pagination.has_next %}
      <li class="page-item">
        <a class="page-link" href="{{ next_url }}">Next</a>
      </li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
  </ul>
</nav>
{% endmacro %}

app/templates/base.html
{% from "_formhelpers.html" import render_form %}
<!DOCTYPE html>
<html>
    <head>
        {% if title %}
        <title>{{ title }}</title>
        {% else %}
        <title>Goalblog</title>
        {% endif %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {{ moment.include_moment() }}
    </head>
    <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main_bp.index') }}">{{_('Home')}}</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user_bp.user', username=current_user.username)}}">{{_('Profile')}}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user_bp.messages') }}">
                        {{_('Messages')}} 
                        {% set unread_messages = current_user.count_unread_messages() %}
                        <span id="unread-messages-count" class="badge bg-secondary">{{ unread_messages if unread_messages }}</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('auth_bp.logout') }}">{{_('Logout')}}</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('auth_bp.login') }}">{{_('Login')}}</a>
                </li class="nav-item active">
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main_bp.explore') }}">{{_('Explore')}}</a>
                </li>
            </ul>
        {% if g.search_form %}
            <form class="form-inline" action="{{url_for('main_bp.search_goals')}}" method="get">
                {{ g.search_form.q(class_="form-control mr-sm-2") }}
                {# {{ g.search_form.submit(class_="btn btn-outline-success my-2 my-sm-0") }} #}
            </form>
        {% endif %}
        </div>
        
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="container-fluid justify-content-start"> 
        {% for category, message in messages %}
            {% if category == "error" %}
                <div  class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div  class="alert alert-primary" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}
    {% endwith %}
    {% if current_user.is_authenticated %}
        {% with tasks = current_user.get_tasks_in_progress() %}
            {% for task in tasks %}
                <div class="alert alert-primary" role="alert"> {{task.description}} 
                
                <span id="task-{{task.id}}-progress">{{task.get_task_progress()}}</span>
                
                </div>
            {% endfor %}
        {% endwith %}
    {% endif %}
    <div class="container-fluid">
    {% block content %} {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" ></script>
    <script>
        async function translateGoal(element, goal_id, users_lang, detected_lang){
       
            var csrf_token = "{{ csrf_token() }}";

            goal_element = document.getElementById("goal-"+goal_id);
            goal_title = goal_element.getElementsByTagName("h5")[0];
            goal_body = goal_element.getElementsByTagName("p")[0];

            let translation = document.createElement("p");
            translation.innerHTML = '<img src="{{ url_for('static', filename='loading.gif') }}">';
            element.replaceWith(translation);

            goal_title_text = goal_title.innerText;
            goal_body_text = goal_body.innerText;
            //goal_texts = [goal_title_text, goal_body_text]

            try{
               const response = await fetch('/translate_goal', {
                method: "POST",
                headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': csrf_token      // because we have CSRFProtect
                    },
                body: JSON.stringify({
                        text_to_translate: goal_body_text,
                        from_language: detected_lang,
                        to_language: users_lang,
                        //texts_to_translate: goal_texts,
                    })
                });

                if (!response.ok) {
                    throw new Error(`Response status: ${response.status}`);
                }
    
                const json = await response.json();
                translation_to_put = json["translation"]

                //translations.forEach((text) => {
                //    translation_to_put += text + "<br>";
                //})
                translation.innerText = translation_to_put          

            } catch (error){
                console.log('There was an error', error);
            }

        }

    function getUserPopup() {
      return new Promise(r => {
        setTimeout(() => r('new data'), 3000);
      })
    }
    async function SetPopoverContent(username) {
        var popup_URI = "{{ url_for('user_bp.mini_profile', username='username_var') }}".replace('username_var',username)
      
        try {
            const response = await fetch(popup_URI);
            if (!response.ok) {
                throw new Error(`Response status: ${response.status}`);
            }

            const text = await response.text();

            return text;

        } catch (error) {
            console.error(error.message);
        }

    }

    function initialize_popup(popover){
        const pop = new bootstrap.Popover(popover, {
            content: 'Loading...',
            html: true,
            trigger: 'hover fokus',
            sanitize: false,
            delay: {hide: 500},
            container: popover, // makes you be able to move cursor on popup without hiding it
        });

        popover.addEventListener('show.bs.popover', async function(ev){
            if (ev.target.popupLoaded){
                return;
            }

            var username = ev.target.innerText.trim();

            const data = await SetPopoverContent(username);
            //const pop = bootstrap.Popover.getInstance(ev.target);
            
            if (pop && data) {
                ev.target.popupLoaded = true;
                pop.setContent({'.popover-body': data});
                ev.target.popupLoaded = true
            }
        });

        popover.addEventListener('shown.bs.popover', function(){
            flask_moment_render_all();
        })
    }

    
    addEventListener("DOMContentLoaded", (event) => { 
        const popover_elements = document.getElementsByClassName('user_popup');
        for (let i = 0; i < popover_elements.length; i++){
            initialize_popup(popover_elements[i]);
        }  
    })

    async function update_message_counter(){
    
        notifications_URI = "{{ url_for('user_bp.notifications', since=0.0)}}"

        try {
            const response = await fetch(notifications_URI);
            if (!response.ok) {
                throw new Error(`Response status: ${response.status}`);
            }

            const notifications = await response.json();
            //console.log(notifications);
            //let counter_value = json["data"];
            for (let i=0; i<notifications.length; i++){
                n = notifications[i];
                if (n['name'] == 'unread_messages_count') {
                    let counter = n['payload']
                    set_unread_messages_counter(counter);
                }
                else if (n['name'] == 'task_progress'){
                    let progress = JSON.parse(n['payload']);
                    set_task_progress(progress.task_id, progress.progress);
                }
            }

        } catch (error) {
            console.error(error.message);
        }
    }

    function set_unread_messages_counter(counter_value){
        counter = document.getElementById("unread-messages-count");
        if (parseInt(counter_value) > 0){
            counter.style.visibility = "visible";
            counter.innerText = counter_value;
        }
        else{
            counter.style.visibility = "hidden";
        }
        
    }

    {% if current_user.is_authenticated %}
        setInterval(update_message_counter, 1000);
        document.addEventListener("DOMContentLoaded", update_message_counter);
    {% endif %}

    function set_task_progress(task_id, progress){
        task_progress_elem = document.getElementById("task-"+task_id+"-progress");
        if (task_progress_elem){
            task_progress_elem.innerText = progress;
        }
    }
    </script>
    </body>
</html>

{# 
async function followFunction(element, user_id) {
            var csrf_token = "{{ csrf_token() }}";
            var follow_URI = "{{ url_for('follow') }}"
            try{
                const response = await fetch('/user/follow', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': csrf_token
                    },
                    body: JSON.stringify({
                        user_id: user_id,
                        action: element.value
                    })
                });

                if (!response.ok) {
                    const message = `An error has occured: ${response.status}`;
                    throw new Error(message);
                }
                var data = await response.json();

                element.value = data['new_follow_status']

            } catch (error){
                console.log('There was an error', error);
            }
        }
 #}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
{% if current_user.is_authenticated %}
  Hello {{ current_user.username }}!
{% endif %}

{% if form %}
<h3>Create goal:</h3>
  <form action="" method="post" novalidate>
    <p>{{ form.hidden_tag() }}
    {{ form.title.label }} <br>
    {{ form.title(size=40) }} <br>
    {% for error in form.title.errors %}
      <span style="color: red">{{ error }}</span>
    {% endfor %} </p>

    <p>{{ form.hidden_tag() }}
    {{ form.body.label }} <br>
    {{ form.body(cols=50, rows=5) }} <br>
    {% for error in form.body.errors %}
      <span style="color: red">{{ error }}</span>
    {% endfor %} </p>

    {{ form.submit }}
  </form>
{% endif %}

<p> Your followings: </p>
{% for following in followings %}
    {{ following.username }} - {{ following.id }}
{% endfor %}

{% for goal in goals %}
    {% include '_goal.html' %} <br>
{% endfor %}


{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block content %}

<h1>Login</h1>

<form action="" method=post novalidate>

    <p>{{ form.hidden_tag() }}
    {{ form.username.label }} <br>
    {{ form.username }} <br>
    {% for error in form.username.errors %}
      <span style="color: red">{{ error }}</span>
    {% endfor %} </p>

    <p>{{ form.password.label }} <br>
    {{ form.password }} <br>
    {% for error in form.password.errors %}
      <span style="color: red">{{ error }}</span>
    {% endfor %} </p> 
    
    {{ form.submit }} 

</form>




{% endblock %}



    {# {{ form.hidden_tag() }}
    {% for field in form %}
        {% if field.widget.input_type != 'hidden' %}        
            {{ field.label }}<br>
            {{ field }}<br>
        {% endif %}
    {% endfor %} #}

app/templates/user.html
{% extends "base.html" %}

{% block content %}


<table>
  <tr>
    <td><img src="{{ user.get_avatar(size=130) }}"></td>
    <td>
    <h1> {{ user.username }} </h1>
    <p>Bio: {{ user.bio if user.bio else "" }}</p>
    <p>Last seen: {{ user.last_seen if user.last_seen else "" }}</p>

    <p> {{ user.username }}'s followers: {{ user.count_followers() }} </p>
    <p> {{ user.username }} follows: {{ user.count_following() }}</p>
    
    {% if current_user.id == user.id %}
        <p><a href="{{ url_for('edit_profile') }}">Edit profile</a></p>
    {% else %}
      
      {% if current_user.is_following(user) %}
        <form action="{{url_for('unfollow', username=user.username)}}" method="post" novalidate>
          {{ form.hidden_tag() }}
          {{ form.submit(value='Unfollow') }}
        </form>
      {% else %}
        <form action="{{url_for('follow', username=user.username)}}" method="post" novalidate>
          {{ form.hidden_tag() }}
          {{ form.submit(value='Follow') }}
        </form>
      {% endif %}
      
    {% endif %}
    </td>
    <td>
    </td>
  </tr>
</table>
<hr>
{% for goal in goals %}
    {% include '_goal.html' %} <br>
{% endfor %}
 


{% endblock %}